/**
 * Seed do Sanity: popula categorias + autor + 5 artigos iniciais.
 *
 * Uso:
 *   1. Em .env.local, preencher:
 *        NEXT_PUBLIC_SANITY_PROJECT_ID
 *        NEXT_PUBLIC_SANITY_DATASET
 *        SANITY_WRITE_TOKEN         (token com permissão de escrita — criar em sanity.io/manage → API → Tokens)
 *   2. npx tsx scripts/seed-sanity.ts
 *
 * Idempotente: usa _id fixo. Rodar várias vezes apenas atualiza; não duplica.
 */

import { createClient } from '@sanity/client';
import { config } from 'dotenv';

// Carrega variáveis de .env.local (preferencial do Next.js) com fallback para .env
config({ path: '.env.local' });
config({ path: '.env' });

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production';
const token = process.env.SANITY_WRITE_TOKEN;

if (!projectId || !token) {
  console.error('✗ Faltam variáveis: NEXT_PUBLIC_SANITY_PROJECT_ID e SANITY_WRITE_TOKEN são obrigatórios.');
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: '2025-01-01',
  token,
  useCdn: false,
});

const key = () => Math.random().toString(36).slice(2, 10);
const p = (text: string) => ({
  _type: 'block', _key: key(), style: 'normal',
  children: [{ _type: 'span', _key: key(), marks: [], text }],
  markDefs: [],
});
const h2 = (text: string) => ({ ...p(text), style: 'h2' });
const h3 = (text: string) => ({ ...p(text), style: 'h3' });
const lead = (text: string) => ({ ...p(text), style: 'lead' });
const bq = (text: string) => ({ ...p(text), style: 'blockquote' });
const li = (text: string, kind: 'bullet' | 'number') => ({ ...p(text), listItem: kind, level: 1 });
const ctaArtigo = (titulo: string, texto: string) => ({
  _type: 'ctaArtigo', _key: key(),
  titulo, texto,
  labelBotao: 'Solicitar diagnóstico',
  href: '/contato',
});
/** Parágrafo com marks inline: [['Texto normal'], ['em', 'itálico'], ['strong', 'negrito'], ['Mais texto']] */
const pMarks = (parts: Array<[string] | [string, string]>) => {
  const children = parts.map(([a, b]) =>
    b !== undefined
      ? { _type: 'span', _key: key(), marks: [a], text: b }
      : { _type: 'span', _key: key(), marks: [], text: a },
  );
  return { _type: 'block', _key: key(), style: 'normal', children, markDefs: [] };
};

/* ============ CATEGORIAS ============ */
const categorias = [
  { _id: 'cat-holding',     titulo: 'Holding',     pilar: 'holding',     slug: 'holding' },
  { _id: 'cat-governanca',  titulo: 'Governança',  pilar: 'governanca',  slug: 'governanca' },
  { _id: 'cat-sucessao',    titulo: 'Sucessão',    pilar: 'sucessao',    slug: 'sucessao' },
  { _id: 'cat-tributario',  titulo: 'Tributário',  pilar: 'tributario',  slug: 'tributario' },
  { _id: 'cat-societario',  titulo: 'Societário',  pilar: 'societario',  slug: 'societario' },
  { _id: 'cat-metodo',      titulo: 'Método',      pilar: 'metodo',      slug: 'metodo' },
].map((c) => ({
  _id: c._id, _type: 'categoria',
  titulo: c.titulo, pilar: c.pilar,
  slug: { _type: 'slug', current: c.slug },
}));

/* ============ AUTOR ============ */
const autor = {
  _id: 'autor-thiago',
  _type: 'autor',
  nome: 'Thiago Seixas',
  slug: { _type: 'slug', current: 'thiago-seixas' },
  oab: 'OAB/SP 249.179',
  bio: 'Advogado com atuação concentrada em direito societário, estruturação patrimonial, holding, governança e organização sucessória. Conduz projetos por método próprio, com diagnóstico antes de estrutura, documentação rigorosa e acompanhamento contínuo. Vargem Grande do Sul — SP.',
  linkedin: 'https://www.linkedin.com/in/thiagoseixas',
};

/* ============ ARTIGOS ============ */

const artigo1 = {
  _id: 'art-holding-faz-sentido',
  _type: 'artigo',
  titulo: 'Quando a holding faz sentido — e quando apenas adiciona complexidade',
  slug: { _type: 'slug', current: 'quando-a-holding-faz-sentido' },
  chamada: 'Três cenários em que a estrutura resolve e dois em que ela só atrapalha. Um texto para quem está avaliando abrir uma holding e já ouviu três opiniões diferentes — e precisa de uma quarta, honesta, antes de decidir.',
  publicadoEm: '2026-04-14T09:00:00-03:00',
  tempoLeitura: 12,
  categoria: { _type: 'reference', _ref: 'cat-holding' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Quando a holding faz sentido — e quando não faz',
  metaDescricao: 'Análise técnica dos cenários em que a holding patrimonial resolve e dos cenários em que apenas adiciona complexidade sem contrapartida.',
  corpo: [
    lead('Perguntar "vale a pena abrir uma holding?" é a pergunta errada. A pergunta certa é: no meu cenário específico, a holding resolve algum problema real — ou apenas adiciona complexidade?'),
    h2('A pergunta certa é "quando"'),
    p('A holding patrimonial virou resposta-padrão nos últimos anos — "abra uma holding" é sugestão ouvida quase antes de o cliente terminar de descrever seu caso. O problema é que essa resposta-padrão ignora o fato de que holding é, antes de tudo, arquitetura jurídica. E toda arquitetura pressupõe um programa — um conjunto específico de problemas a resolver.'),
    p('Sem problema a resolver, a holding não é solução. É apenas uma pessoa jurídica a mais, com contabilidade, obrigações acessórias, declarações, custos de manutenção e exposição tributária próprias. Quem constitui holding sem programa claro, em poucos anos, desconstitui ou reorganiza.'),
    p('Este texto percorre os cenários em que a holding costuma resolver — e os cenários em que ela costuma apenas adicionar complexidade. Não é exaustivo, mas cobre a maioria dos casos que aparecem em consulta.'),
    h2('Três cenários em que a holding resolve'),
    h3('Cenário 1 — Sucessão patrimonial a organizar'),
    p('O caso mais clássico e também o mais robusto. Família com patrimônio consolidado, herdeiros definidos, e interesse em antecipar parte da transmissão patrimonial ainda em vida, reduzindo ITCMD e evitando o inventário futuro.'),
    p('Aqui a holding funciona por três razões simultâneas:'),
    li('Permite doação com reserva de usufruto das quotas, transmitindo a nua-propriedade aos herdeiros mantendo gestão e rendimentos com o titular', 'bullet'),
    li('Aplica cláusulas protetivas (incomunicabilidade, impenhorabilidade, inalienabilidade, reversão) sobre as quotas doadas', 'bullet'),
    li('Substitui a abertura de inventário por uma alteração contratual simples no momento do falecimento, poupando tempo, custos e conflitos processuais', 'bullet'),
    p('Esse cenário costuma ter pay-off claro. Em geral, o ponto de equilíbrio aparece em patrimônio organizável a partir de R$ 3-5 milhões, mas isso varia muito com composição dos bens e cenário familiar.'),
    h3('Cenário 2 — Proteção de participações societárias'),
    p('Empresário com participação em sociedades operacionais que gera lucros relevantes e precisa de três coisas ao mesmo tempo: separar patrimônio pessoal do operacional, organizar o fluxo de dividendos e construir blindagem lícita contra riscos empresariais.'),
    p('Nesse cenário, a holding entra como acionista/sócia das operacionais, recebe os dividendos (com a vantagem tributária da isenção no PJ receptor) e administra esses recursos separadamente do patrimônio das operacionais — que continuam expostas ao risco empresarial.'),
    h3('Cenário 3 — Gestão familiar a profissionalizar'),
    p('Família com múltiplos bens, múltiplos membros e decisões compartilhadas que, sem estrutura, viram conflito em cada movimento. A holding aqui não é solução tributária — é instrumento de governança.'),
    p('Quando os bens estão todos na pessoa jurídica, as regras de gestão ficam registradas em contrato social e acordo de sócios. Os conflitos deixam de ser discussões familiares vagas para virarem questões procedimentais claras.'),
    ctaArtigo('Quer avaliar se seu cenário justifica uma holding?', 'O diagnóstico inicial responde essa pergunta com base no seu caso concreto — patrimônio, composição familiar, sociedades, objetivos — não com regra geral.'),
    h2('Dois cenários em que a holding só atrapalha'),
    h3('Cenário A — Patrimônio de baixa complexidade'),
    p('Pessoa física com um ou dois imóveis, herdeiros em quantidade reduzida, sem sociedades operacionais, e sem cenário sucessório próximo. Nesse caso, o custo anual da holding — contabilidade, obrigações acessórias, contador especializado, declarações — costuma superar largamente qualquer economia tributária potencial.'),
    p('E pior: a estrutura adiciona exposição. Qualquer erro em declaração de IRPJ, falha em obrigação acessória ou demora em registro pode gerar multa que, sozinha, inviabiliza o benefício projetado da holding.'),
    h3('Cenário B — Expectativa puramente tributária'),
    p('Cliente que chega com a tese de que "abrir holding reduz imposto". Em alguns cenários, reduz mesmo — mas raramente é o fator decisivo, e quase nunca é suficiente por si só para justificar a estrutura. Quando a única motivação é economia de imposto, a holding costuma decepcionar em três frentes:'),
    li('A economia projetada no papel frequentemente não se realiza na prática', 'number'),
    li('A Receita Federal e estados vêm apertando a fiscalização sobre operações com propósito exclusivamente tributário, e holdings montadas como "simulação" são desconstituídas com multas agravadas', 'number'),
    li('Sem programa sucessório ou de governança real, a estrutura não gera os benefícios não-tributários que costumam ser os mais relevantes no médio prazo', 'number'),
    bq('Holding não é sinônimo de economia tributária. É arquitetura societária que, em alguns cenários, traz economia tributária como consequência — nunca como objetivo exclusivo.'),
    h2('Como decidir na prática'),
    p('A decisão sobre constituir holding só é honesta depois de três passos:'),
    li('Diagnóstico patrimonial, tributário, societário e familiar, com levantamento completo do que existe', 'number'),
    li('Identificação de objetivos reais — sucessão, proteção, gestão, tributação — em ordem de prioridade', 'number'),
    li('Análise comparativa entre constituir e não constituir, com projeção de custos, riscos e benefícios em horizonte de 5-10 anos', 'number'),
    p('Se esses três passos apontarem para holding, faz sentido seguir. Se apontarem para outras ferramentas (testamento, doação direta, reorganização societária sem holding), faz sentido seguir por elas. E se apontarem para não fazer nada agora, isso também é resposta legítima — e, às vezes, a mais técnica.'),
    h2('Conclusão'),
    p('Holding patrimonial não é decisão automática. É arquitetura que, bem escolhida e bem executada, resolve problemas concretos — e que, mal escolhida, adiciona complexidade sem resolver nada. Entre a narrativa generalista de "abra uma holding" e a recusa dogmática a estruturas societárias, existe o caminho técnico: diagnóstico, programa, desenho, execução e acompanhamento.'),
    p('Esse é o caminho que este escritório percorre em cada caso — começando pelo diagnóstico, e só depois decidindo pela estrutura.'),
  ],
};

const artigo2 = {
  _id: 'art-acordo-socios-sete-clausulas',
  _type: 'artigo',
  titulo: 'Acordo de sócios: sete cláusulas que previnem os conflitos mais caros',
  slug: { _type: 'slug', current: 'acordo-de-socios-sete-clausulas' },
  chamada: 'Tag along, drag along, buy-sell, lock-up, não-concorrência, resolução de impasses e valuation. Sete cláusulas que separam sociedades organizadas de sociedades em litígio permanente — e por que cada uma delas importa.',
  publicadoEm: '2026-04-08T09:00:00-03:00',
  tempoLeitura: 11,
  categoria: { _type: 'reference', _ref: 'cat-governanca' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Acordo de sócios: 7 cláusulas que previnem conflitos',
  metaDescricao: 'Análise técnica das cláusulas de proteção em acordo de sócios: tag along, drag along, buy-sell, lock-up, não-concorrência, resolução de impasses e valuation.',
  corpo: [
    lead('A maior parte dos conflitos societários que viram processo nasce de acordos de sócios genéricos, mal-redigidos ou inexistentes. Este texto percorre sete cláusulas centrais que, bem construídas, evitam a maior parte desses litígios.'),
    h2('Por que o contrato social não basta'),
    p('O contrato social contém o mínimo legal exigido para a existência da sociedade: objeto, capital, participações, administração. O acordo de sócios regula o que o contrato não alcança — as regras de convivência entre sócios, as proteções recíprocas, as fórmulas de saída, os critérios de decisão em situações de tensão.'),
    p('São documentos complementares, não concorrentes. Uma sociedade sofisticada tem ambos — e os revisa periodicamente.'),
    h2('1. Tag along — direito de venda conjunta'),
    p('Protege os sócios minoritários. Se um sócio majoritário recebe proposta para vender sua participação, o minoritário tem direito de vender a sua nas mesmas condições (ou em condições proporcionais acordadas).'),
    p('Sem tag along, o minoritário fica "preso" quando o majoritário vende para terceiro — e o novo sócio pode ter perfil e interesses completamente diferentes, sem que o minoritário tenha qualquer poder de veto ou saída.'),
    h2('2. Drag along — obrigação de venda conjunta'),
    p('O inverso do tag along. Em determinadas condições (percentual mínimo de votos favoráveis, preço mínimo, momento específico), o sócio majoritário pode obrigar o minoritário a vender.'),
    p('Parece duro — mas é instrumento essencial em cenário de M&A: compradores estratégicos frequentemente exigem 100% da sociedade, e sem drag along, um único minoritário pode inviabilizar uma venda benéfica para todos os demais.'),
    h2('3. Buy-sell — fórmula de saída'),
    p('Define antecipadamente como a participação de um sócio será avaliada e comprada em caso de saída (voluntária, por falecimento, por incapacidade, por conflito). A fórmula pode ser baseada em múltiplos de EBITDA, valor patrimonial, avaliação por laudo independente — cada opção com implicações próprias.'),
    p('Sem buy-sell, qualquer saída vira negociação do zero — e quase sempre vira disputa judicial.'),
    h2('4. Lock-up — bloqueio temporário de venda'),
    p('Impede que sócios vendam suas quotas por um período determinado (3, 5, 7 anos). Útil em sociedades recém-constituídas ou que acabaram de receber investimento: protege a estabilidade da composição societária enquanto o negócio amadurece.'),
    p('Combinado com direito de preferência — que obriga o sócio que quer vender a primeiro oferecer aos demais, em condições equivalentes — o lock-up cria uma camada extra de proteção contra mudanças abruptas.'),
    ctaArtigo('Sua sociedade tem acordo de sócios robusto?', 'Se a resposta é "não" ou "não sei", vale começar pelo diagnóstico. Acordo bem-feito se constrói na harmonia — não no conflito.'),
    h2('5. Não-concorrência — proteção da sociedade'),
    p('Define o que os sócios podem e não podem fazer em paralelo à sociedade. Um sócio pode abrir um negócio concorrente? Pode trabalhar para um concorrente? Pode participar de cliente ou fornecedor?'),
    p('A cláusula deve ser proporcional: restrições excessivas podem ser declaradas nulas por violação ao livre exercício profissional. A redação técnica é delicada — restrições relativas a território, prazo, atividade específica e objeto societário costumam ser os eixos da validade.'),
    h2('6. Resolução de impasses (deadlock)'),
    p('Em sociedades com dois sócios 50/50, ou com blocos que se equilibram, decisões críticas podem travar. A cláusula de deadlock define o protocolo de resolução: escalonamento para mediação, arbitragem, ou — em último caso — buy-sell forçado.'),
    p('O chamado "shotgun clause" é um mecanismo forte: em impasse grave, um sócio oferece um preço por suas quotas. O outro tem duas opções: aceitar o preço e comprar, ou vender suas próprias quotas pelo mesmo preço. Garante que alguém sai — e impede que a sociedade seja paralisada indefinidamente.'),
    h2('7. Valuation — método de avaliação'),
    p('Quase toda cláusula que envolve compra/venda de quotas depende de uma fórmula de valuation. Fixar esse método no acordo evita que toda saída vire discussão pericial longa.'),
    p('Os métodos mais usados: múltiplo de EBITDA (comum em sociedades operacionais maduras), valor patrimonial ajustado (holdings patrimoniais), DCF simplificado, ou laudo de avaliador independente indicado por comissão paritária. Cada método tem prós, contras e aplicabilidades específicas.'),
    bq('Acordo de sócios não se constrói no otimismo. Se constrói na premissa de que, em algum momento, algum sócio vai querer coisa diferente do outro — e o acordo escrito é o que impede que isso vire processo.'),
    h2('Conclusão'),
    p('As sete cláusulas acima não são exaustivas — acordos sofisticados têm 20-30 cláusulas ou mais, adaptadas ao caso. Mas as sete formam o núcleo mínimo de proteção recíproca em sociedades com mais de um sócio.'),
    p('O momento certo de construir (ou revisar) o acordo é na fase de harmonia, não no conflito aberto. Acordo construído em conflito é mediação difícil; acordo construído em harmonia é arquitetura eficiente — e é o que efetivamente previne litígio no futuro.'),
  ],
};

const artigo3 = {
  _id: 'art-itcmd-planejamento-sucessorio',
  _type: 'artigo',
  titulo: 'ITCMD no planejamento sucessório: o que muda por estado e como decidir',
  slug: { _type: 'slug', current: 'itcmd-planejamento-sucessorio' },
  chamada: 'Alíquotas, bases de cálculo, doação com reserva de usufruto e os limites do planejamento lícito. Diferenças regionais relevantes e decisões práticas que separam planejamento eficiente de economia ilusória.',
  publicadoEm: '2026-04-02T09:00:00-03:00',
  tempoLeitura: 10,
  categoria: { _type: 'reference', _ref: 'cat-sucessao' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'ITCMD no planejamento sucessório — diferenças por estado',
  metaDescricao: 'Alíquotas, bases de cálculo, doação com reserva de usufruto e os limites do planejamento sucessório lícito. Diferenças regionais e decisões práticas.',
  corpo: [
    lead('ITCMD é o imposto que mais aparece em conversas de planejamento sucessório — e também o que mais gera expectativa errada. Este texto organiza o essencial: como funciona, como varia por estado, e onde o planejamento lícito realmente entrega economia.'),
    h2('O que é ITCMD e quem cobra'),
    p('ITCMD — Imposto sobre Transmissão Causa Mortis e Doação — incide sobre toda transferência gratuita de bens ou direitos, seja em vida (doação) ou por falecimento (causa mortis). É imposto estadual, regido pela legislação de cada estado da federação.'),
    p('A Constituição Federal fixa o teto de 8% para a alíquota, mas dentro desse teto cada estado define sua própria alíquota, base de cálculo, isenções e procedimentos.'),
    h2('Diferenças relevantes entre estados'),
    p('O ITCMD é um dos tributos com maior variação regional do Brasil. Alguns pontos de atenção:'),
    li('Alíquotas variam de 4% a 8% — e muitos estados já sinalizaram intenção de subir para o teto', 'bullet'),
    li('Alguns estados aplicam alíquota progressiva (quanto maior o patrimônio, maior a alíquota); outros aplicam alíquota única', 'bullet'),
    li('Bases de cálculo variam: alguns usam valor de mercado, outros o valor venal (IPTU/ITR), outros o valor declarado', 'bullet'),
    li('Isenções e reduções para doação entre ascendentes/descendentes variam largamente', 'bullet'),
    p('Em São Paulo, por exemplo, a alíquota atual é 4% uniforme para a maioria dos casos — uma das mais baixas do país. Em estados como Rio de Janeiro e Ceará, alíquotas progressivas podem chegar a 8%. Em Minas Gerais, 5%.'),
    h2('O momento de planejar: agora ou depois'),
    p('A pergunta prática é: vale pagar ITCMD agora (na doação em vida) ou esperar pagar depois (no inventário)?'),
    p('A análise envolve três variáveis principais:'),
    li('Alíquota atual vs. alíquota esperada no momento do falecimento — estados têm aumentado alíquotas, o que tende a favorecer a doação agora', 'number'),
    li('Base de cálculo atual vs. esperada — patrimônio que se valoriza aumenta a base futura (desfavorável a esperar)', 'number'),
    li('Custos e tempo de inventário — doação em vida evita esses custos; essa economia é parte do ganho', 'number'),
    p('Em muitos cenários, a combinação dessas variáveis torna a doação antecipada significativamente mais eficiente que o inventário — mas isso precisa ser calculado caso a caso, não assumido.'),
    h2('Doação com reserva de usufruto'),
    p('Instrumento clássico do planejamento sucessório. O titular doa a nua-propriedade aos herdeiros, mantendo para si o usufruto — direito de usar, administrar e receber os rendimentos do bem ou das quotas, enquanto viver.'),
    p('Vantagens:'),
    li('Transmissão efetuada em vida, com incidência de ITCMD sobre o valor da nua-propriedade (geralmente 70% do valor total na maioria dos estados)', 'bullet'),
    li('Manutenção do controle e dos rendimentos pelo titular', 'bullet'),
    li('Extinção automática do usufruto no falecimento, sem novo fato gerador de ITCMD (regra geral em quase todos os estados)', 'bullet'),
    li('Possibilidade de aplicar cláusulas protetivas (incomunicabilidade, impenhorabilidade, inalienabilidade, reversão)', 'bullet'),
    ctaArtigo('Seu estado é o mais eficiente para planejar?', 'O diagnóstico sucessório considera a geografia tributária do seu caso — e aponta quando e como a doação antecipada faz sentido.'),
    h2('Limites do planejamento lícito'),
    p('Nem toda "economia" de ITCMD é lícita. Operações sem substância econômica, criadas exclusivamente para evitar o imposto, podem ser desconsideradas pela Fazenda. Os principais limites:'),
    li('Operações simuladas ou sem propósito negocial real podem ser desconstituídas', 'bullet'),
    li('Doações antecipadas feitas poucos meses antes do falecimento em estados que reavaliam a base tendem a gerar questionamento', 'bullet'),
    li('Estruturas em holdings que não exercem atividade real, criadas apenas para "fragmentar" a base de cálculo, são de fiscalização crescente', 'bullet'),
    li('Operações com imóveis devem respeitar valor de mercado — subavaliação intencional é infração', 'bullet'),
    p('O planejamento lícito distingue-se do que é simulação pela existência de substância: patrimônio real, operações reais, estrutura coerente com a atividade e com a família.'),
    h2('E a holding patrimonial?'),
    p('A holding é o veículo mais comum em planejamento sucessório estruturado. Ao centralizar bens (imóveis, participações) em pessoa jurídica e doar as quotas em vez dos bens diretamente, permite:'),
    li('Maior flexibilidade para aplicar cláusulas protetivas', 'bullet'),
    li('Regime tributário diferenciado na gestão corrente dos bens (lucro presumido em muitos casos)', 'bullet'),
    li('Substituição do inventário por alteração contratual no falecimento — economia processual significativa', 'bullet'),
    p('Mas a holding sozinha não é sinônimo de economia de ITCMD. A economia vem da combinação correta entre holding, doação com usufruto, cláusulas protetivas e aproveitamento das alíquotas estaduais vigentes.'),
    bq('Planejamento sucessório feito em vida, com calma e diagnóstico prévio, é qualitativamente superior a qualquer decisão tomada sob pressão de evento. O tempo aqui é o maior aliado do contribuinte.'),
    h2('Conclusão'),
    p('ITCMD é imposto que recompensa antecipação e planejamento técnico. As decisões corretas dependem de mapear patrimônio, entender o estado de domicílio, avaliar o cenário legislativo, e combinar instrumentos — não de aplicar fórmulas genéricas.'),
    p('O melhor momento de fazer esse trabalho é antes do evento sucessório, em harmonia familiar, com espaço para discussão e ajustes. Depois, quando o evento ocorre, as opções são sempre menores — e os custos, sempre maiores.'),
  ],
};

const artigo4 = {
  _id: 'art-integralizacao-imoveis',
  _type: 'artigo',
  titulo: 'Integralização de imóveis em holding: ITBI, ganho de capital e pontos de atenção',
  slug: { _type: 'slug', current: 'integralizacao-imoveis-holding' },
  chamada: 'A conferência de imóveis à pessoa jurídica tem implicações tributárias que nem sempre são visíveis no ato. Análise técnica dos pontos críticos: ITBI condicional, ganho de capital, Tema 796 do STF e escolha de regime de apuração.',
  publicadoEm: '2026-03-26T09:00:00-03:00',
  tempoLeitura: 10,
  categoria: { _type: 'reference', _ref: 'cat-holding' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Integralização de imóveis em holding — ITBI e ganho de capital',
  metaDescricao: 'Implicações tributárias da conferência de imóveis à holding: ITBI condicional, ganho de capital, Tema 796 do STF, regime de apuração.',
  corpo: [
    lead('Integralizar imóveis na holding parece operação simples — transferir bens da pessoa física para a pessoa jurídica em troca de quotas. Mas as implicações tributárias são mais complexas do que a aparência sugere. Este texto percorre os pontos críticos.'),
    h2('O que é integralização de imóveis'),
    p('Quando uma pessoa física aporta imóveis no capital de uma pessoa jurídica, em contrapartida recebe quotas ou ações dessa PJ. É o que se chama integralização de capital com bens — na prática, uma conferência de propriedade em troca de participação societária.'),
    p('O objetivo típico em holdings patrimoniais é centralizar os bens em estrutura única, preparando sucessão, facilitando gestão e, em alguns casos, otimizando tributação corrente (aluguéis, ganhos de capital).'),
    h2('ITBI — imunidade condicional (Tema 796 do STF)'),
    p('A Constituição prevê, no artigo 156, §2º, I, imunidade de ITBI para transmissão de bens ou direitos incorporados ao patrimônio de pessoa jurídica em realização de capital. Parece inequívoco — mas há uma ressalva: a imunidade não se aplica se a atividade preponderante da PJ for compra e venda, locação ou arrendamento mercantil de imóveis.'),
    p('O Supremo Tribunal Federal, no julgamento do Tema 796 (2020), fixou entendimento de que essa imunidade é condicional — mesmo na integralização de capital, se a holding tiver como atividade preponderante operações imobiliárias, o ITBI é devido.'),
    p('Na prática, isso significa que holdings puramente patrimoniais (que administram os próprios bens) costumam ter a imunidade reconhecida. Mas holdings que recebem aluguéis como atividade principal estão em zona de risco — e o tratamento varia por município.'),
    h2('Como provar atividade não-preponderante'),
    p('A análise é feita com base na receita bruta da PJ nos três anos anteriores e nos três anos posteriores à operação (ou, no caso de PJ nova, nos três anos posteriores). Se mais de 50% da receita vier de operações imobiliárias, perde-se a imunidade.'),
    p('Essa análise temporal significa que a integralização hoje pode ser questionada por fiscalização futura, se a atividade efetiva da holding se revelar predominantemente imobiliária. Daí a importância de planejar o objeto social e a atividade real com cuidado.'),
    ctaArtigo('Sua holding está na zona segura da imunidade?', 'O diagnóstico analisa objeto social, atividade efetiva e histórico de receita — e aponta os ajustes necessários antes da integralização.'),
    h2('Ganho de capital na integralização'),
    p('Além do ITBI, há outra camada: o imposto de renda sobre ganho de capital. Quando a pessoa física integraliza imóvel pelo valor de mercado (maior que o valor de aquisição corrigido), gera-se ganho de capital tributável.'),
    p('A legislação (Lei 9.249/95, art. 23) permite escolher entre duas alternativas:'),
    li('Integralizar pelo valor declarado no IR da pessoa física — sem incidência de ganho de capital no ato, mas mantendo o valor histórico como base para alienações futuras pela holding', 'number'),
    li('Integralizar pelo valor de mercado — com incidência de IR sobre o ganho (15% a 22,5%), mas atualizando a base para operações futuras', 'number'),
    p('A escolha depende do horizonte de alienação, do perfil do imóvel e do cenário sucessório. Integralizar pelo valor histórico é o padrão em holdings patrimoniais de longo prazo; integralizar pelo valor de mercado pode ser vantajoso quando a alienação é prevista em horizonte curto.'),
    h2('Regime tributário da holding'),
    p('Depois da integralização, a holding passa a tributar os rendimentos dos bens (aluguéis, ganhos de capital em alienações futuras) conforme seu regime de apuração: lucro presumido, lucro real ou Simples Nacional.'),
    p('Holdings patrimoniais com receita predominantemente imobiliária geralmente operam em lucro presumido, com tributação efetiva que pode variar entre 11% e 14% sobre receita bruta de aluguéis — significativamente inferior aos até 27,5% que a pessoa física pagaria. Mas o Simples Nacional raramente se aplica — e a escolha entre presumido e real depende do perfil específico.'),
    h2('Cuidados documentais'),
    p('Alguns pontos que costumam ser fontes de problema posterior:'),
    li('Averbação tempestiva da transferência nas matrículas dos imóveis', 'bullet'),
    li('Coerência entre objeto social, atividade efetiva e receita real (para manutenção da imunidade de ITBI)', 'bullet'),
    li('Declaração correta no IR da pessoa física e no Imposto de Renda da Pessoa Jurídica (IRPJ) da holding', 'bullet'),
    li('Avaliação dos imóveis por laudo técnico quando a operação exceder determinados valores ou envolver imóveis específicos', 'bullet'),
    bq('Integralização de imóveis em holding não é operação que admite improvisação. Cada escolha técnica — valor de conferência, regime tributário, atividade preponderante — tem implicações que se revelam nos anos seguintes.'),
    h2('Conclusão'),
    p('A integralização é a porta de entrada da holding patrimonial e, por isso, merece o cuidado técnico de qualquer porta de entrada: se mal construída, compromete tudo o que vier depois. As decisões sobre ITBI, ganho de capital, regime tributário e documentação devem ser tomadas com visão de médio e longo prazo — não só do momento da operação.'),
    p('Os benefícios sucessórios, societários e tributários da holding só se concretizam quando a integralização é feita corretamente. Caso contrário, o que seria estrutura vira passivo — às vezes maior que o benefício pretendido.'),
  ],
};

const artigo5 = {
  _id: 'art-diagnostico-antes-estrutura',
  _type: 'artigo',
  titulo: 'Diagnóstico antes de estrutura: por que não começamos pela holding',
  slug: { _type: 'slug', current: 'diagnostico-antes-de-estrutura' },
  chamada: 'A ordem dos fatores altera o resultado. Por que o escritório se recusa a começar pela estrutura — e o que isso muda na prática, em qualidade de projeto e custo no longo prazo.',
  publicadoEm: '2026-03-19T09:00:00-03:00',
  tempoLeitura: 7,
  categoria: { _type: 'reference', _ref: 'cat-metodo' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Diagnóstico antes de estrutura — método de trabalho',
  metaDescricao: 'Por que o trabalho começa pelo diagnóstico, não pela holding. Como essa ordem muda a qualidade do projeto e reduz custos no longo prazo.',
  corpo: [
    lead('A demanda típica do cliente novo é simples: "quero abrir uma holding". Mas a primeira resposta deste escritório raramente é "vamos abrir". É "vamos fazer o diagnóstico primeiro". Este texto explica por que.'),
    h2('Demanda e necessidade são coisas diferentes'),
    p('O cliente que procura o escritório já pensou no problema, já consultou outras fontes, já formou uma hipótese sobre a solução. Quando ele diz "quero abrir uma holding", está oferecendo ao mesmo tempo um diagnóstico (o problema é X) e uma prescrição (a solução é Y).'),
    p('O advogado que simplesmente aceita essa prescrição perde a oportunidade de questionar o diagnóstico. E diagnósticos leigos são frequentemente incompletos — não por má-fé, mas porque quem faz o diagnóstico é o mesmo quem vive o problema, sem o recuo necessário.'),
    p('Aceitar a prescrição sem revisar o diagnóstico é um dos erros mais comuns e mais caros em advocacia consultiva.'),
    h2('O que o diagnóstico descobre que a demanda esconde'),
    p('Em projetos reais, o diagnóstico frequentemente revela:'),
    li('Que o problema central não era o que o cliente descreveu — muitas vezes a demanda da holding é, na verdade, um problema de governança familiar não-tratado', 'bullet'),
    li('Que existe um passivo oculto que inviabiliza a operação proposta até ser resolvido (documentação pendente, registro não-averbado, regime de bens mal-compreendido)', 'bullet'),
    li('Que a arquitetura ideal é diferente da imaginada — em vez de uma holding, pode fazer sentido duas; em vez de integralizar todos os bens, integralizar apenas parte', 'bullet'),
    li('Que a urgência é outra — o cliente queria otimização tributária, mas há risco sucessório iminente que merece atenção prioritária', 'bullet'),
    p('Sem diagnóstico, começa-se pela solução errada para o problema errado — e se descobre isso tarde, quando o custo de corrigir já multiplicou.'),
    h2('O que o diagnóstico envolve'),
    p('Em termos práticos, um diagnóstico sério inclui:'),
    li('Entrevista estruturada de 90-120 minutos para compreender cenário patrimonial, societário, familiar e os objetivos reais do cliente', 'number'),
    li('Solicitação e análise dos documentos críticos — contratos sociais atualizados, escrituras, IR da PF e das PJs, certidões', 'number'),
    li('Mapeamento das pendências — o que está irregular, o que precisa ser resolvido antes de qualquer avanço', 'number'),
    li('Primeira visão da arquitetura viável — com alternativas, trade-offs, horizonte de execução', 'number'),
    li('Proposta técnica com escopo, cronograma e entregáveis identificáveis', 'number'),
    p('Esse trabalho leva de duas a oito semanas, dependendo da complexidade. E é cobrado — por ser trabalho técnico substantivo, não "orçamento gratuito".'),
    ctaArtigo('Prefere começar pelo diagnóstico ou pela estrutura?', 'A proposta técnica parte sempre de uma conversa inicial. Em 90 minutos entendemos juntos se a melhor entrada é pelo diagnóstico, ou se o cenário já está suficientemente claro para avançar direto.'),
    h2('O custo de pular o diagnóstico'),
    p('Projetos que começam pela estrutura sem diagnóstico prévio costumam apresentar, em 12-24 meses, uma ou mais destas situações:'),
    li('Alteração contratual significativa para corrigir arquitetura mal-escolhida', 'bullet'),
    li('Passivos tributários não-previstos, descobertos pela fiscalização ou em nova operação', 'bullet'),
    li('Conflitos familiares ou societários que a estrutura não previu porque o diagnóstico familiar não foi feito', 'bullet'),
    li('Necessidade de desconstituir parte da estrutura — operação cara e tecnicamente complicada', 'bullet'),
    p('Em termos financeiros, o custo de corrigir costuma ser 3 a 10 vezes maior que o custo do diagnóstico inicial bem-feito. Em termos de tempo, pode significar um a dois anos de retrabalho.'),
    h2('O valor do "não" honesto'),
    p('Uma função importante do diagnóstico é também apontar quando a estrutura pretendida não faz sentido. Nem todo cenário justifica holding. Nem toda família precisa de governança formal. Nem toda reorganização societária é a prioridade do momento.'),
    p('Dizer "não faz sentido agora" — quando é verdade — é parte do serviço. Vale mais para o cliente no longo prazo do que vender uma solução mal-dimensionada apenas porque foi pedida.'),
    bq('Estruturação patrimonial e societária não é venda de produto. É arquitetura — e arquitetura começa pela compreensão do programa, não pela escolha do material.'),
    h2('Conclusão'),
    p('Começar pelo diagnóstico é mais lento, mais caro no curto prazo e menos "entregável" do que começar pela estrutura. Em compensação, reduz retrabalho, aumenta a probabilidade de acerto técnico e transforma a relação cliente-escritório de transacional em consultiva.'),
    p('Essa é a forma de trabalhar deste escritório. Nem todo cliente está disposto a esse ritmo — e está tudo bem. Mas para quem valoriza arquitetura sobre improviso, é o caminho que costuma entregar melhor resultado em cinco, dez, vinte anos.'),
  ],
};

/* ============ ARTIGO 6 ============ */
const artigo6 = {
  _id: 'art-cisao-incorporacao-fusao',
  _type: 'artigo',
  titulo: 'Reorganização societária: cisão, incorporação e fusão — comparativo prático',
  slug: { _type: 'slug', current: 'cisao-incorporacao-fusao-comparativo' },
  chamada: 'Três operações, três efeitos distintos. Quando usar cada uma, quais os impactos tributários, e os cuidados documentais que evitam autuações futuras — um guia prático sobre decisões que costumam ser tomadas intuitivamente.',
  publicadoEm: '2026-03-12T09:00:00-03:00',
  tempoLeitura: 11,
  categoria: { _type: 'reference', _ref: 'cat-tributario' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Cisão, incorporação e fusão — comparativo prático',
  metaDescricao: 'Diferenças práticas entre cisão, incorporação e fusão. Quando usar cada uma, efeitos tributários, prazos e riscos de autuação.',
  corpo: [
    lead('Cisão, incorporação e fusão são operações frequentemente confundidas na conversa corporativa. São tecnicamente distintas — e a escolha errada tem consequências tributárias, contratuais e societárias difíceis de reverter.'),
    h2('As três operações em uma frase'),
    p('<b>Cisão</b> separa: uma sociedade transfere parte (cisão parcial) ou totalidade (cisão total) do patrimônio para uma ou mais sociedades. A sociedade cindida pode continuar existindo ou ser extinta.'),
    p('<b>Incorporação</b> absorve: uma sociedade (incorporada) tem seu patrimônio absorvido por outra (incorporadora). A incorporada deixa de existir; a incorporadora continua, agora maior.'),
    p('<b>Fusão</b> combina: duas ou mais sociedades se unem, formando uma nova. Todas as anteriores deixam de existir; nasce uma terceira, que herda o patrimônio das antecessoras.'),
    h2('Quando usar cada uma'),
    h3('Cisão — quando faz sentido'),
    p('Útil quando há necessidade de separar atividades distintas, preparar venda parcial, segregar riscos ou dividir patrimônio entre sócios que seguem caminhos diferentes. Também comum em reorganizações societárias sucessórias, onde parte do patrimônio é destinada a um ramo da família.'),
    p('Cuidado: cisão pode gerar ITBI sobre transferência de imóveis (exceto quando se aplica imunidade específica) e exige laudo de avaliação em muitos casos. A escolha entre cisão parcial e total muda o tratamento.'),
    h3('Incorporação — quando faz sentido'),
    p('Clássica em aquisição estratégica: uma empresa compra outra e incorpora seu patrimônio. Também usada para simplificar estruturas societárias onde múltiplas PJs perderam razão de existir separadas. A operação concentra ativos, passivos, contratos e contingências em uma única sociedade.'),
    p('Atenção aos <i>skeletons</i>: passivos ocultos da incorporada viram passivos da incorporadora. Due diligence prévia não é opcional.'),
    h3('Fusão — quando faz sentido'),
    p('Mais rara no direito brasileiro por exigir formação de sociedade nova. Útil em combinações entre partes equivalentes que preferem começar sob nova marca/estrutura a uma absorção de uma pela outra. Também pode ter razões simbólicas importantes em negociações estratégicas.'),
    p('Custo operacional maior que incorporação — há uma PJ nova para constituir, registros cadastrais novos, CNAE e CNPJ novos.'),
    ctaArtigo('Avaliando uma reorganização?', 'O diagnóstico analisa o cenário completo e aponta qual operação — cisão, incorporação, fusão ou alternativa fora desse trio — melhor resolve o problema concreto.'),
    h2('Efeitos tributários comparados'),
    p('Todas as três podem ser feitas em regime de <b>sucessão tributária</b> — a sociedade resultante assume débitos tributários das antecessoras. Em operações entre partes relacionadas com propósito não-mercantil, a Receita pode desconsiderar se não houver substância econômica.'),
    p('A regra geral é que operações bem-estruturadas, com propósito negocial identificável e documentação completa, são neutras em IRPJ e CSLL. Mas há exceções importantes:'),
    li('Cisão com transferência de imóveis pode gerar ITBI (análise caso a caso)', 'bullet'),
    li('Ganho de capital em cisão com diferimento exige opção expressa e cumprimento de requisitos específicos', 'bullet'),
    li('Incorporação de sociedade com prejuízo fiscal tem limitações de aproveitamento pela incorporadora (art. 33, Decreto-Lei 2.341/87)', 'bullet'),
    li('Fusão gera necessidade de baixa das PJs antecessoras em todas as esferas, com potencial de encontro contábil de resultados', 'bullet'),
    h2('Cuidados documentais obrigatórios'),
    p('Toda reorganização societária exige conjunto documental rigoroso: protocolo e justificação, laudos de avaliação, deliberação dos sócios por quórum apropriado, alterações contratuais ou estatuto da sociedade resultante, publicações quando exigidas, registro na Junta Comercial.'),
    p('Omissões documentais aqui não são falhas que se corrigem depois — abrem espaço para questionamento de credores, sócios dissidentes e fisco. Prazos prescricionais para impugnação podem chegar a vários anos.'),
    h2('Conclusão'),
    p('Cisão, incorporação e fusão são ferramentas — não sinônimos. A operação certa é aquela que resolve o problema específico da reorganização com menor custo tributário, menor exposição a contingências e maior clareza documental.'),
    p('Quando há dúvida entre duas alternativas, a análise comparativa detalhada de custos e riscos é barata perto do custo de reverter uma operação mal-escolhida.'),
  ],
};

/* ============ ARTIGO 7 ============ */
const artigo7 = {
  _id: 'art-profissionalizacao-empresa-familiar',
  _type: 'artigo',
  titulo: 'Profissionalização da empresa familiar: quatro instrumentos de governança',
  slug: { _type: 'slug', current: 'profissionalizacao-empresa-familiar' },
  chamada: 'Protocolo familiar, conselho de família, conselho consultivo e acordo de sócios. Quatro instrumentos que organizam o que costuma virar conflito — e que, juntos, diferenciam empresa familiar profissional de empresa familiar em improviso.',
  publicadoEm: '2026-03-05T09:00:00-03:00',
  tempoLeitura: 9,
  categoria: { _type: 'reference', _ref: 'cat-governanca' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Profissionalização da empresa familiar — 4 instrumentos',
  metaDescricao: 'Protocolo familiar, conselho de família, conselho consultivo e acordo de sócios — instrumentos que profissionalizam a empresa familiar.',
  corpo: [
    lead('Empresa familiar não se profissionaliza por acaso — nem se profissionaliza só contratando gestor externo. Profissionalização é arquitetura, e essa arquitetura tem ferramentas específicas.'),
    h2('O problema que esses instrumentos resolvem'),
    p('Em quase todas as empresas familiares, há sobreposição de três papéis distintos: o papel de <b>familiar</b> (membro da família), o papel de <b>sócio</b> (detentor de capital) e o papel de <b>gestor</b> (administrador da operação). Quando essas camadas se confundem, decisões empresariais viram decisões familiares, heranças viram brigas, e reuniões de família viram comitês de gestão desorganizados.'),
    p('Os quatro instrumentos abaixo separam essas camadas — cada uma com regras próprias, fórum próprio, responsabilidade própria.'),
    h2('1. Protocolo familiar'),
    p('Documento central que registra os <b>princípios, valores e regras fundamentais</b> da família em relação ao patrimônio e à empresa. Trata de: como membros da família se relacionam com a empresa, como se incorpora a próxima geração, como se lida com cônjuges e parentes por afinidade, como se resolvem conflitos entre ramos familiares.'),
    p('Não é um documento de sócios — é um documento de família. Sua força vem menos da execução judicial e mais do acordo moral entre as partes: quando todos assinam, a força é a palavra e a expectativa mútua.'),
    h3('Quando faz sentido'),
    p('Sempre que há mais de uma geração envolvida ou quando há sinais de conflito latente entre membros. Famílias com um único dono ainda em gestão plena raramente precisam — famílias em transição para segunda geração, quase sempre precisam.'),
    h2('2. Conselho de família'),
    p('Fórum formal onde os membros da família discutem e deliberam sobre temas que afetam a relação família-empresa: sucessão de gestão, entrada de novos membros, educação da próxima geração, filantropia familiar, valores e visão de longo prazo.'),
    p('Estrutura típica: reuniões trimestrais ou semestrais, pauta prévia, ata escrita, presidente rotativo. Em famílias com mais de seis membros, pode ter subcomitês (educação, sucessão, comunicação).'),
    h3('Diferença crítica'),
    p('Conselho de família <b>não se confunde</b> com conselho consultivo da empresa nem com reunião de sócios. São três fóruns distintos, cada um com competência específica — mesmo que as pessoas se repitam em vários deles.'),
    h2('3. Conselho consultivo (ou de administração)'),
    p('Órgão de governança <i>da empresa</i> (não da família), composto por sócios, membros externos e, em alguns casos, executivos-chave. Sua função é orientar a gestão estratégica: aprovar orçamento, avaliar desempenho do CEO, decidir sobre investimentos relevantes, supervisionar riscos.'),
    p('Em empresas familiares, incluir <b>conselheiros externos</b> — profissionais sem laço familiar — costuma ser o movimento de maior impacto na qualidade das decisões. Traz perspectiva de fora, quebra vieses familiares, profissionaliza o debate.'),
    ctaArtigo('Sua empresa familiar está pronta para profissionalizar?', 'O diagnóstico de governança avalia quais dos quatro instrumentos fazem sentido construir — e em que ordem, com que prazo, com que participantes.'),
    h2('4. Acordo de sócios'),
    p('Instrumento societário — já detalhado em artigo próprio do escritório. Em empresas familiares, cobre especificidades: entrada de herdeiros em quotas doadas, tag along e drag along em cenário sucessório, regras de cessão entre ramos, valuation em saída forçada por conflito familiar.'),
    p('O acordo de sócios é o único dos quatro com <b>executabilidade judicial robusta</b>. Por isso, as regras mais sensíveis (proteções financeiras, cláusulas de saída, mecanismos de impasse) ficam nele — e o protocolo familiar trata das camadas que são mais relação do que execução.'),
    h2('Articulação entre os quatro'),
    p('Protocolo familiar e acordo de sócios devem ser <b>consistentes entre si</b>. Conselho de família e conselho consultivo não podem ter sobreposição de competências — cada um decide coisas diferentes. Valores e regras gerais no protocolo; regras de governança empresarial nos conselhos; regras societárias no acordo de sócios.'),
    p('Quando bem articulados, os quatro instrumentos formam um sistema — e a família empresária passa a funcionar com previsibilidade. Quando mal articulados, geram conflito sobre qual fórum decide o quê.'),
    h2('Conclusão'),
    p('Profissionalizar não é sobre contratar gestor de fora. É sobre construir um <b>sistema</b> onde as camadas família, sociedade e gestão operam com regras claras e fóruns apropriados. Os quatro instrumentos são as peças desse sistema — e todos podem ser construídos em paralelo ao crescimento natural do negócio.'),
    p('O custo de construir é sempre menor que o custo de não construir — mas este último só aparece quando o conflito chega, e aí já é tarde.'),
  ],
};

/* ============ ARTIGO 8 ============ */
const artigo8 = {
  _id: 'art-holding-pura-mista-operacional',
  _type: 'artigo',
  titulo: 'Holding pura, mista e operacional: qual é a certa para cada caso',
  slug: { _type: 'slug', current: 'holding-pura-mista-operacional' },
  chamada: 'Três arquiteturas societárias, três casos de uso distintos. A escolha errada custa imposto, flexibilidade e segurança jurídica — e é mais comum do que parece.',
  publicadoEm: '2026-02-26T09:00:00-03:00',
  tempoLeitura: 9,
  categoria: { _type: 'reference', _ref: 'cat-holding' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Holding pura, mista ou operacional — qual escolher',
  metaDescricao: 'Comparativo técnico entre holding pura, mista e operacional. Qual tipo faz sentido para cada perfil de patrimônio e programa sucessório.',
  corpo: [
    lead('Holding não é um conceito único. É uma família de arquiteturas — e escolher a errada é um dos enganos mais caros em planejamento patrimonial.'),
    h2('Definições que importam'),
    h3('Holding pura'),
    p('Pessoa jurídica cujo objeto social é exclusivamente <b>deter participações em outras sociedades</b>. Não exerce atividade operacional, não fatura por prestação de serviços, não aluga bens próprios. Seu caixa vem essencialmente de dividendos distribuídos pelas controladas e, eventualmente, de ganhos em alienação de participações.'),
    h3('Holding mista'),
    p('Pessoa jurídica que <b>combina</b> detenção de participações societárias com atividade operacional própria — tipicamente administração de imóveis (aluguel) e gestão de investimentos financeiros, mas pode incluir outras atividades compatíveis. É a forma mais comum em planejamento patrimonial familiar no Brasil.'),
    h3('Holding operacional'),
    p('Termo usado para pessoa jurídica que é, simultaneamente, detentora de participações e <b>operadora principal de uma atividade empresarial</b> — por exemplo, a sociedade-mãe de um grupo empresarial que também comercializa produtos ou presta serviços. É o modelo clássico de conglomerados.'),
    h2('Qual escolher — guia rápido'),
    h3('Cenário 1 — Família com múltiplas empresas operacionais'),
    p('Pai fundador com três empresas operacionais separadas; quer organizar sucessão e centralizar governança. <b>Escolha típica:</b> holding pura. Detém as participações das três, deixa as operacionais operando normalmente, concentra decisões estratégicas num único veículo, facilita a doação de quotas da holding aos herdeiros.'),
    h3('Cenário 2 — Patrimônio misto: imóveis + participações'),
    p('Empresário com portfólio imobiliário (alugado) e participações em sociedades operacionais. <b>Escolha típica:</b> holding mista. Integralização dos imóveis para regime tributário mais eficiente na locação (lucro presumido), participações consolidadas no mesmo veículo, planejamento sucessório integrado.'),
    p('Atenção fundamental: atividade preponderante precisa ser planejada para preservar imunidade de ITBI na integralização (Tema 796 STF).'),
    h3('Cenário 3 — Empresa familiar como negócio principal'),
    p('Família que opera a própria atividade empresarial e quer organizar a sucessão mantendo o negócio central funcionando. <b>Escolha típica:</b> estrutura em duas camadas — holding pura no topo, detendo a operacional. A holding recebe os dividendos (isentos), serve de veículo sucessório, e a operacional continua focada na atividade.'),
    p('Colocar operação e participações na mesma pessoa jurídica (holding operacional) costuma ser pior: mistura riscos empresariais com patrimônio familiar consolidado.'),
    ctaArtigo('Qual holding faz sentido no seu cenário?', 'A escolha entre pura, mista e operacional depende da composição do patrimônio e dos objetivos. O diagnóstico inicial responde essa pergunta com base em análise técnica concreta.'),
    h2('Implicações tributárias'),
    p('Cada tipo tem perfil tributário distinto:'),
    li('<b>Pura</b> — caixa vem de dividendos (isentos) + eventuais ganhos de capital. Regime típico: lucro presumido, com baixa base tributável efetiva.', 'bullet'),
    li('<b>Mista</b> — receita de aluguéis tributada no regime escolhido (presumido costuma ser eficiente, 11%-14% efetivos), combinada com dividendos isentos.', 'bullet'),
    li('<b>Operacional</b> — receita de atividade empresarial tributada normalmente; regime pode ser presumido ou real, dependendo do porte e do perfil da operação.', 'bullet'),
    h2('Armadilhas comuns'),
    p('<b>1. Holding mista confundida com operacional.</b> Se a holding patrimonial começa a exercer atividade preponderante imobiliária sem planejamento, perde a imunidade de ITBI — e a integralização de novos imóveis vira fato gerador.'),
    p('<b>2. Holding operacional como veículo sucessório único.</b> Colocar a operação empresarial dentro da holding familiar concentra riscos. Uma ação judicial contra a operação pode atingir o patrimônio sucessório.'),
    p('<b>3. Holding pura sem propósito.</b> Se a única função é deter 100% de uma única sociedade operacional sem nenhum benefício sucessório, governança ou tributário claro, é apenas pessoa jurídica a mais sem agregar valor.'),
    h2('Conclusão'),
    p('Pura, mista ou operacional — a escolha não é estética nem tributária em si. É consequência do <b>programa</b>: que problema a holding precisa resolver? Para que família? Com que patrimônio? Em que horizonte?'),
    p('Quando o programa está claro, o tipo de holding se revela quase automaticamente. Quando o programa não está claro, qualquer escolha vira apostar no escuro.'),
  ],
};

/* ============ ARTIGO 9 ============ */
const artigo9 = {
  _id: 'art-doacao-reserva-usufruto',
  _type: 'artigo',
  titulo: 'Doação com reserva de usufruto: como usar bem no planejamento sucessório',
  slug: { _type: 'slug', current: 'doacao-com-reserva-de-usufruto' },
  chamada: 'Instrumento clássico de antecipação de herança. Estrutura, efeitos e armadilhas comuns que esvaziam o objetivo pretendido — um guia para quem está considerando usar a ferramenta.',
  publicadoEm: '2026-02-19T09:00:00-03:00',
  tempoLeitura: 10,
  categoria: { _type: 'reference', _ref: 'cat-sucessao' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Doação com reserva de usufruto — guia prático',
  metaDescricao: 'Doação com reserva de usufruto: estrutura, ITCMD sobre nua-propriedade, cláusulas protetivas e armadilhas comuns no planejamento sucessório.',
  corpo: [
    lead('Doação com reserva de usufruto é o mecanismo mais utilizado em planejamento sucessório brasileiro. É também um dos mais mal-compreendidos — e usar mal esvazia o benefício que justifica a operação.'),
    h2('Como funciona na prática'),
    p('A pessoa titular de um bem (ou de quotas societárias) divide a propriedade em duas camadas: a <b>nua-propriedade</b> e o <b>usufruto</b>. A nua-propriedade é transferida por doação a um donatário (tipicamente herdeiro direto); o usufruto permanece com o doador.'),
    p('Consequências imediatas:'),
    li('O donatário torna-se titular formal do bem — mas <b>não exerce direitos sobre ele</b> enquanto o usufruto estiver vigente.', 'bullet'),
    li('O doador mantém <b>uso, administração e percepção de rendimentos</b> — ou seja, continua usando o imóvel, recebendo os aluguéis, recebendo os dividendos das quotas.', 'bullet'),
    li('No falecimento do doador (ou no termo do usufruto, se houver prazo), o usufruto se extingue automaticamente e o donatário consolida a propriedade plena.', 'bullet'),
    h2('Benefícios do mecanismo'),
    h3('1. Antecipação sucessória com controle'),
    p('O doador transmite o patrimônio em vida sem abrir mão da gestão. Resolve um problema clássico: "quero organizar a sucessão, mas preciso continuar decidindo e recebendo enquanto vivo".'),
    h3('2. Economia tributária sucessória'),
    p('O ITCMD incide na doação sobre o <b>valor da nua-propriedade</b>, que a maioria dos estados calcula em 2/3 (66,67%) do valor total do bem. Isso já representa base de cálculo menor que o ITCMD causa mortis, que em inventário incidiria sobre 100% do valor atualizado.'),
    p('Em muitos estados, a extinção do usufruto por morte do doador <b>não é fato gerador</b> de novo ITCMD — a economia é definitiva. Em alguns estados, é fato gerador sobre 1/3 restantes — mas ainda pode ser vantajoso em projeções de longo prazo.'),
    h3('3. Evita inventário sobre o bem'),
    p('Como o donatário já era nu-proprietário e consolida automaticamente, o bem <b>não entra em inventário</b>. Economia de tempo, honorários advocatícios e custas processuais. Reduz também a probabilidade de conflito entre herdeiros.'),
    h3('4. Aplicação de cláusulas protetivas'),
    p('O momento da doação é a oportunidade de aplicar cláusulas de incomunicabilidade, impenhorabilidade, inalienabilidade e reversão sobre o bem doado — protegendo-o contra eventos pessoais do donatário (divórcio, dívidas).'),
    ctaArtigo('Quer entender como estruturar a doação no seu caso?', 'O diagnóstico sucessório analisa o cenário patrimonial e familiar, e aponta se, quando e como a doação com reserva de usufruto faz sentido — com as cláusulas adequadas.'),
    h2('Armadilhas comuns que esvaziam o benefício'),
    h3('1. Não considerar a colação na partilha'),
    p('Doação a descendente importa adiantamento da legítima (art. 544, Código Civil). Se o doador não dispensar a colação expressamente, o valor do bem doado será trazido à partilha no inventário futuro — para equalização entre os demais herdeiros.'),
    p('A dispensa da colação precisa ser <b>expressa</b> no documento da doação, e precisa respeitar o limite da parte disponível do doador (50% do patrimônio quando há herdeiros necessários).'),
    h3('2. Ignorar a legítima'),
    p('Doação que invade a legítima (a parte indisponível destinada aos herdeiros necessários) pode ser <b>reduzida judicialmente</b> depois. A análise prévia da proporção doada versus patrimônio remanescente é essencial para evitar nulidades parciais.'),
    h3('3. Usufruto sem definição de direitos e obrigações'),
    p('Quem paga IPTU durante o usufruto? Quem faz reformas? Pode alugar? Quem recebe o aluguel? Essas perguntas, se não forem respondidas no documento, viram discussão — e a relação doador-donatário pode deteriorar.'),
    p('A escritura/contrato de doação bem-redigido responde explicitamente a cada ponto. Silêncio aqui é problema futuro.'),
    h3('4. Não articular com cláusulas protetivas'),
    p('Doar sem incomunicabilidade significa que, em divórcio do donatário, o cônjuge pode reivindicar meação sobre a nua-propriedade (dependendo do regime). Doar sem impenhorabilidade significa que credores do donatário podem penhorar a nua-propriedade — com leilão após extinção do usufruto.'),
    p('As cláusulas não são opcionais quando o objetivo é proteção patrimonial — são essenciais. Aplicá-las no momento da doação é tecnicamente mais simples que tentar aplicá-las depois.'),
    h3('5. Confundir usufruto vitalício com usufruto puro e simples'),
    p('Usufruto pode ser vitalício ou por prazo certo. A maioria dos casos usa vitalício — mas em cenários específicos (filho menor, doador em idade avançada), prazo certo pode ser melhor. A escolha é técnica e depende do caso.'),
    h2('Quando NÃO usar'),
    p('A doação com reserva de usufruto não é solução universal. Situações em que é mais prejudicial do que útil:'),
    li('Doador jovem com patrimônio ainda em formação — o custo tributário imediato pode não compensar', 'bullet'),
    li('Donatário com risco relevante (dívidas, processos, divórcio iminente) — a doação pode virar alvo', 'bullet'),
    li('Patrimônio que se valoriza mais lentamente que a alíquota de ITCMD do estado permitiria recuperar', 'bullet'),
    li('Famílias sem definição clara de herdeiros — doar sem saber o quadro completo é antecipar problema', 'bullet'),
    h2('Conclusão'),
    p('Doação com reserva de usufruto é ferramenta potente, mas não é plug-and-play. Requer análise prévia do patrimônio, dos herdeiros, da legítima, do regime de bens, das cláusulas adequadas, do ITCMD estadual e do momento certo.'),
    p('Bem estruturada, entrega antecipação sucessória com controle mantido, economia tributária e proteção patrimonial. Mal estruturada, gera ITCMD pago à toa, conflitos familiares e exposição patrimonial que a própria doação deveria evitar.'),
  ],
};

/* ============ ARTIGO 10 ============ */
const artigo10 = {
  _id: 'art-alteracao-contratual-ltda',
  _type: 'artigo',
  titulo: 'Alteração contratual de LTDA: quóruns, registros e armadilhas comuns',
  slug: { _type: 'slug', current: 'alteracao-contratual-ltda-quoruns' },
  chamada: 'A maior parte das nulidades societárias nasce em alterações mal conduzidas. Os quóruns, prazos e formalidades que não podem falhar — um guia técnico direto ao ponto.',
  publicadoEm: '2026-02-12T09:00:00-03:00',
  tempoLeitura: 7,
  categoria: { _type: 'reference', _ref: 'cat-societario' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Alteração contratual de LTDA — quóruns e armadilhas',
  metaDescricao: 'Quóruns legais por matéria, prazos de registro, ordem das operações e armadilhas comuns em alteração contratual de sociedade limitada.',
  corpo: [
    lead('Alteração contratual parece operação simples — mas é onde mais aparecem nulidades societárias descobertas anos depois, em momentos caros. Este texto organiza o essencial.'),
    h2('Os três quóruns que você precisa saber'),
    p('A LTDA opera com três quóruns legais principais, definidos no Código Civil e aplicáveis conforme a matéria:'),
    h3('Quórum simples — maioria dos presentes'),
    p('Aplicável a matérias ordinárias não-reservadas por lei a quórum especial. Exemplos: nomeação de administrador não-sócio, escolha de auditor, outras deliberações cotidianas.'),
    h3('Quórum qualificado — 3/4 do capital social (art. 1.076, I, CC)'),
    p('Aplicável a <b>alterações contratuais em geral</b> — modificação de cláusulas do contrato social, inclusão de nova atividade, alteração de administração, sede, etc. É o quórum mais usado na prática.'),
    h3('Quórum de maioria absoluta — mais de 50% do capital (art. 1.076, II, CC)'),
    p('Aplicável a: nomeação e destituição de administradores, aprovação das contas, e matérias específicas. Note que é 50%+1 — não é a maioria dos presentes.'),
    h3('Atenção ao contrato social específico'),
    p('O próprio contrato pode estabelecer <b>quóruns maiores</b> do que os legais (mais restritivos), e muitos contratos bem-redigidos o fazem. Se o contrato exige unanimidade para determinada matéria, a lei não substitui — prevalece a cláusula contratual.'),
    ctaArtigo('Vai fazer uma alteração contratual?', 'Revisão técnica prévia identifica o quórum correto, a ordem dos atos e os registros necessários — evitando que a operação seja questionada depois.'),
    h2('Ordem das operações'),
    p('Alterações contratuais que envolvem múltiplas mudanças (ex.: entrada de sócio + aumento de capital + alteração de administração) podem ser documentadas em ato único, mas a <b>ordem da narrativa</b> tem consequências práticas:'),
    li('Se o novo sócio vota em matéria da sua própria admissão, há vício formal', 'number'),
    li('Aumento de capital integralizado por sócio pré-existente altera as proporções — e isso precisa vir antes de outras deliberações que dependam do novo quadro', 'number'),
    li('Alterações em administração devem ser aprovadas pelo quórum correto da matéria anterior, não pelo quórum pós-alteração', 'number'),
    p('Ordem errada é o tipo de problema que só aparece em due diligence ou em conflito — e aí já é tarde.'),
    h2('Registro e prazos'),
    p('O ato alterado precisa ser <b>arquivado na Junta Comercial</b> competente. O prazo geral é de 30 dias a contar da assinatura; após esse prazo, o registro é feito, mas seus efeitos retroagem apenas à data de apresentação — não à data do ato.'),
    p('Alterações não-averbadas <b>não produzem efeito contra terceiros</b>. Se você alterou o quadro societário e não averbou, perante terceiros (credores, clientes, fisco) o quadro antigo continua vigente.'),
    h3('Efeitos fiscais e cadastrais</b>'),
    p('Após a averbação, é preciso atualizar CNPJ (Receita Federal), alvará municipal, inscrição estadual (se aplicável), regime tributário de nova atividade. Omitir essas etapas pode gerar autuação por exercício de atividade não-cadastrada.'),
    h2('Armadilhas que aparecem em due diligence'),
    li('<b>Atas sem assinatura de todos os quotistas exigidos</b> — se a deliberação exigia 3/4 e só têm 60% assinando, há vício', 'bullet'),
    li('<b>Cessão de quotas não-averbada</b> — contra terceiros, o cedente ainda é sócio; para fins fiscais, as obrigações continuam no quadro antigo', 'bullet'),
    li('<b>Aumento de capital integralizado em bens sem laudo</b> — quando exigido, a ausência de laudo técnico questiona o valor da integralização', 'bullet'),
    li('<b>Alteração de objeto social sem atualização de alvarás</b> — exposição tributária e de licenciamento', 'bullet'),
    li('<b>Administrador designado sem que o contrato permita</b> — se o contrato exige administração exclusiva por sócio, a nomeação de não-sócio exige alteração contratual prévia, não apenas assembleia', 'bullet'),
    h2('Conclusão'),
    p('Alteração contratual é momento técnico — e justamente por parecer simples, é onde mais se erra. A revisão preventiva antes de cada alteração é barata frente ao custo de descobrir nulidade em operação futura (due diligence, M&A, sucessão).'),
    p('Documentação rigorosa, quórum correto, ordem coerente, registro tempestivo, atualizações cadastrais completas. Quando esses cinco passos são seguidos, a alteração é limpa. Quando um deles falha, é potencial problema aguardando descoberta.'),
  ],
};

/* ============ ARTIGO 11 ============ */
const artigo11 = {
  _id: 'art-lucro-presumido-holding',
  _type: 'artigo',
  titulo: 'Lucro presumido em holding: requisitos e análise de viabilidade',
  slug: { _type: 'slug', current: 'lucro-presumido-em-holding' },
  chamada: 'Regime tributário costuma ser o fator de maior economia na holding patrimonial — quando calculado corretamente e aplicado dentro dos limites legais. Análise técnica de quando faz sentido e quando não faz.',
  publicadoEm: '2026-02-05T09:00:00-03:00',
  tempoLeitura: 9,
  categoria: { _type: 'reference', _ref: 'cat-tributario' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Lucro presumido em holding — quando faz sentido',
  metaDescricao: 'Requisitos, cálculo e limites do regime de lucro presumido em holdings patrimoniais. Análise comparativa com lucro real e impacto prático.',
  corpo: [
    lead('A diferença entre tributar uma holding em lucro presumido ou real pode ser de 5 a 15 pontos percentuais sobre a receita — em patrimônios relevantes, são centenas de milhares de reais por ano. Merece análise técnica, não intuição.'),
    h2('O que é lucro presumido'),
    p('Regime de apuração do IRPJ e da CSLL em que o lucro tributável é calculado por <b>presunção sobre a receita bruta</b>, aplicando percentuais legais fixos — dispensando contabilidade do lucro real e reduzindo obrigações acessórias.'),
    p('Para holdings patrimoniais, os percentuais de presunção relevantes são:'),
    li('<b>Aluguéis de imóveis:</b> 32% da receita bruta (IRPJ) e 32% (CSLL)', 'bullet'),
    li('<b>Ganhos de capital:</b> 100% do ganho (tributa valor integral, não presumido)', 'bullet'),
    li('<b>Dividendos recebidos:</b> isentos (não tributados pela holding)', 'bullet'),
    h2('Como fica a conta na prática'),
    p('Para uma holding que recebe exclusivamente aluguéis em lucro presumido:'),
    li('Base tributável presumida: 32% da receita bruta', 'bullet'),
    li('IRPJ: 15% sobre essa base + 10% adicional sobre o que exceder R$ 60.000 no trimestre', 'bullet'),
    li('CSLL: 9% sobre a mesma base presumida', 'bullet'),
    li('PIS: 0,65% sobre receita bruta', 'bullet'),
    li('COFINS: 3% sobre receita bruta', 'bullet'),
    p('<b>Carga efetiva estimada:</b> 11% a 14% da receita bruta de aluguel. Comparado aos até 27,5% que a pessoa física pagaria diretamente, a diferença é significativa.'),
    h2('Requisitos e limites'),
    h3('Receita bruta anual até R$ 78 milhões'),
    p('O limite legal vigente. Acima desse valor, a obrigatoriedade é de lucro real. Holdings patrimoniais familiares raramente chegam perto desse limite — é improvável ser fator restritivo.'),
    h3('Atividades vedadas'),
    p('Algumas atividades não podem optar pelo presumido: instituições financeiras, securitização, factoring, empresas que aufiram rendimentos no exterior, entre outras. Holdings patrimoniais puras e mistas geralmente não têm restrição por atividade.'),
    h3('Opção no início do ano-calendário'),
    p('A opção pelo regime é feita no início do ano-calendário e <b>não pode ser alterada durante o ano</b>. Decidiu presumido em janeiro, fica presumido até dezembro. Planejamento tributário é decisão antecipada, não reativa.'),
    ctaArtigo('Lucro presumido ou real — qual melhor no seu caso?', 'A análise comparativa considera receita projetada, composição de custos e horizonte patrimonial. O diagnóstico tributário responde caso a caso.'),
    h2('Quando o presumido deixa de valer a pena'),
    h3('1. Margem operacional baixa'),
    p('O presumido tributa por presunção — mesmo se a holding teve custos altos, paga imposto sobre 32% da receita. Se a margem real é menor que a presumida (cenário de custos altos de manutenção, reformas, imóveis ociosos), o real pode ser mais eficiente.'),
    p('Regra prática: se a margem efetiva da holding é consistentemente inferior a 20%, vale simular o real.'),
    h3('2. Prejuízos fiscais recorrentes'),
    p('Lucro real permite compensação de prejuízos fiscais de anos anteriores (limitada a 30% do lucro tributável). Lucro presumido não — não há compensação de prejuízos.'),
    p('Holdings em fase de estruturação, com receitas ainda baixas e despesas de implementação altas, podem acumular prejuízo fiscal no presumido sem aproveitá-lo nunca. No real, esse prejuízo vira crédito para anos seguintes.'),
    h3('3. Ganhos de capital significativos'),
    p('No presumido, ganho de capital é tributado 100% (não presumido) + adicional de IR, e ainda há IRPJ e CSLL sobre lucro operacional sem compensação. Em anos com alienação grande de imóvel, o cálculo comparativo com real pode ser favorável a este.'),
    h2('Comparativo simplificado'),
    p('Para ilustração — holding com R$ 1 milhão anual de aluguéis, sem outras receitas, custos operacionais de R$ 100 mil/ano:'),
    p('<b>Lucro presumido:</b> tributa 32% × R$ 1 milhão = R$ 320 mil. Sobre isso, IRPJ + CSLL efetivos ≈ R$ 80 mil. Mais PIS/COFINS sobre receita ≈ R$ 36 mil. <b>Total aproximado: R$ 116 mil</b> (11,6% da receita).'),
    p('<b>Lucro real:</b> lucro contábil = R$ 900 mil. IRPJ (25%) + CSLL (9%) = 34% × R$ 900 mil ≈ R$ 306 mil. PIS/COFINS no regime não-cumulativo (1,65% + 7,6%) ≈ R$ 92 mil, com créditos. <b>Total aproximado: R$ 380-400 mil</b> (38-40% da receita).'),
    p('Neste cenário simples, presumido é dramaticamente mais eficiente. Mas o inverso pode acontecer — o cálculo depende fortemente da composição real.'),
    h2('Revisão anual'),
    p('A opção pelo regime é anual. Faz sentido <b>reavaliar a cada ano</b>, especialmente quando há:'),
    li('Mudança significativa no portfólio (aquisição/alienação de imóveis grandes)', 'bullet'),
    li('Reforma ou renovação com custos altos programados', 'bullet'),
    li('Entrada ou saída de receitas relevantes', 'bullet'),
    li('Mudança no regime tributário de empresa controlada pela holding', 'bullet'),
    h2('Conclusão'),
    p('Lucro presumido é, na grande maioria das holdings patrimoniais familiares, o regime correto. Mas "na grande maioria" não é "em todas". A conta precisa ser feita no caso específico — com base em receita projetada, custos operacionais, composição de ativos e horizonte patrimonial.'),
    p('Essa análise é trabalho técnico rápido (algumas horas em cenários simples, um dia em cenários complexos) e tem retorno direto em economia tributária concreta. Vale a pena fazer.'),
  ],
};

/* ============ ARTIGO 12 ============ */
const artigo12 = {
  _id: 'art-conselho-de-familia',
  _type: 'artigo',
  titulo: 'Conselho de família: quando faz sentido, como estruturar, o que evitar',
  slug: { _type: 'slug', current: 'conselho-de-familia' },
  chamada: 'Instrumento central de governança familiar — poderoso quando bem-estruturado, inútil ou contraproducente quando não. Um guia técnico sobre a ferramenta mais subestimada da governança familiar.',
  publicadoEm: '2026-01-29T09:00:00-03:00',
  tempoLeitura: 8,
  categoria: { _type: 'reference', _ref: 'cat-governanca' },
  autor: { _type: 'reference', _ref: 'autor-thiago' },
  metaTitulo: 'Conselho de família — como estruturar',
  metaDescricao: 'Quando faz sentido montar um conselho de família, como estruturá-lo, erros comuns que o tornam inútil — guia prático de governança familiar.',
  corpo: [
    lead('Conselho de família é ferramenta que aparece em muitos projetos de governança, mas raramente é estruturada com o cuidado que exige. Este texto aborda o essencial: quando faz sentido, como montar, e o que não confundir.'),
    h2('O que é e o que não é'),
    p('Conselho de família é um <b>fórum formal</b> em que membros da família se reúnem periodicamente para discutir e deliberar sobre temas que afetam a relação entre família e patrimônio (ou entre família e empresa). Tem pauta escrita, periodicidade definida, participantes conhecidos, registros por ata.'),
    p('Não é: reunião informal de jantar, grupo de WhatsApp, comitê de gestão da empresa, reunião de sócios. Cada um desses é outra coisa — e confundir é onde costuma-se errar.'),
    h2('Quando faz sentido montar'),
    p('Conselho de família faz sentido quando:'),
    li('Há <b>mais de uma geração</b> envolvida no patrimônio ou na empresa', 'bullet'),
    li('Há <b>membros não-gestores</b> com participação relevante (herdeiros que receberam quotas mas não trabalham no negócio)', 'bullet'),
    li('Existem <b>decisões compartilhadas recorrentes</b> sobre gestão patrimonial, educação dos mais jovens, filantropia, sucessão', 'bullet'),
    li('Há <b>histórico ou risco de conflito</b> entre membros — conselho bem-estruturado é mecanismo preventivo', 'bullet'),
    li('Há <b>ramos familiares distintos</b> (vários filhos com seus próprios núcleos) e é preciso equilibrar interesses', 'bullet'),
    p('Não faz sentido: famílias muito pequenas com uma única geração atuante, patrimônio baixo onde o custo de operar o conselho supera o benefício, cenários de conflito já judicializado (neste caso, é mediação, não conselho).'),
    h2('Como estruturar'),
    h3('Composição'),
    p('Pergunta prática: <b>quem participa?</b> Em famílias pequenas, todos os membros adultos. Em famílias maiores, pode fazer sentido representação por ramo (um por núcleo familiar), rotativa ou fixa. Cônjuges — inclusão é decisão familiar; não há resposta certa, mas precisa ser definida no início.'),
    p('Menores geralmente não participam de decisões, mas podem participar de reuniões educativas específicas, para preparar a próxima geração.'),
    h3('Periodicidade'),
    p('Trimestral é o padrão. Semestral também funciona em famílias com menor volume de temas. Mensal costuma ser excessivo — vira burocracia sem substância.'),
    p('Além das reuniões regulares, o conselho pode ter <b>convocações extraordinárias</b> para temas urgentes (crise familiar, falecimento, decisão estratégica imediata).'),
    h3('Pauta'),
    p('Pauta-padrão costuma incluir: revisão do protocolo familiar, discussão de temas sucessórios, decisões sobre filantropia familiar, preparação da próxima geração, temas levantados por qualquer membro na pauta aberta.'),
    p('O que <b>não</b> entra na pauta do conselho de família: decisões operacionais da empresa (isso é conselho consultivo ou diretoria), decisões societárias específicas que exigem assembleia formal (isso é reunião de sócios).'),
    ctaArtigo('Pensando em estruturar governança familiar?', 'O diagnóstico de governança familiar avalia se o conselho faz sentido — e, se fizer, como montar com o desenho certo para o seu caso.'),
    h3('Formalidade'),
    p('Ata por reunião é obrigatória. Presidente e secretário rotativos ou fixos (decisão familiar). Em cenários mais formais, atas são registradas em livro próprio. Em cenários menos formais, ficam arquivadas digitalmente, com versão assinada por todos os presentes.'),
    h3('Relação com outros fóruns'),
    p('O conselho de família precisa ter <b>competência clara e delimitada</b>. Não decide sobre gestão empresarial (cabe ao conselho consultivo ou diretoria). Não substitui reunião de sócios (que tem formalidades societárias específicas). Não toma decisões judiciais (que são do Judiciário, obviamente).'),
    p('Quando essa delimitação não existe, o conselho vira espaço de disputa — todos querem levar seus problemas para lá, e o conselho não consegue decidir nada porque tudo é de sua alçada aparente.'),
    h2('Erros comuns que tornam o conselho inútil'),
    h3('1. Fundir conselho de família com conselho consultivo'),
    p('São fóruns com naturezas distintas. Fundir cria conflito de papéis: você está ali como filho do fundador ou como representante da empresa? A decisão é de família ou de gestão? Manter separados preserva a lógica de cada um.'),
    h3('2. Montar conselho sem protocolo familiar prévio'),
    p('Conselho sem protocolo é fórum sem regras. Fica procurando o que fazer, discutindo formato a cada reunião, e rapidamente cai em desuso. O protocolo familiar estabelece as regras do jogo; o conselho executa-as.'),
    h3('3. Excesso de formalidade no início'),
    p('Tentar montar um conselho muito sofisticado no primeiro ano — muitos comitês, atas extensas, regras complexas — gera rejeição natural. Começar simples (reunião trimestral com pauta básica, ata enxuta) e evoluir é o caminho.'),
    h3('4. Não incluir as novas gerações'),
    p('Conselho que só tem a primeira geração perde relevância no momento da transição. A inclusão gradual dos filhos adultos é parte da função do conselho — preparar a próxima fase da família.'),
    h3('5. Usar o conselho como instrumento de controle'),
    p('Quando um membro tenta usar o conselho para impor suas decisões — ou quando vira extensão informal da reunião de sócios — a credibilidade desaparece. Conselho é fórum de <b>discussão e alinhamento</b>, não de imposição.'),
    h2('Conclusão'),
    p('Conselho de família bem-estruturado é uma das ferramentas mais eficientes para reduzir conflito familiar ao longo do tempo. Não é sobre decidir rápido — é sobre criar um espaço onde decisões compartilhadas <b>podem ser tomadas</b> com regras claras, em vez de explodirem em reuniões informais ou grupos de WhatsApp.'),
    p('Como todo instrumento de governança, exige disciplina para funcionar. Mas quando funciona, a família opera com qualidade diferente — e a diferença aparece especialmente em momentos críticos: sucessão, venda de empresa, crise familiar.'),
  ],
};

const artigos = [artigo1, artigo2, artigo3, artigo4, artigo5, artigo6, artigo7, artigo8, artigo9, artigo10, artigo11, artigo12];

/* ============ EXECUÇÃO ============ */
async function main() {
  console.log(`→ Conectando ao projeto ${projectId} (dataset: ${dataset})`);

  const docs = [...categorias, autor, ...artigos];
  let tx = client.transaction();
  for (const d of docs) {
    tx = tx.createOrReplace(d as any);
  }

  try {
    await tx.commit();
    console.log(`✓ ${categorias.length} categorias inseridas/atualizadas`);
    console.log(`✓ 1 autor inserido/atualizado`);
    console.log(`✓ ${artigos.length} artigos inseridos/atualizados (plano editorial completo)`);
    console.log('\nSeed concluído. Abra o Studio em /studio para revisar.');
  } catch (err) {
    console.error('✗ Erro ao executar seed:', err);
    process.exit(1);
  }
}

main();
